name: bus_booking_app
description: "A modern bus booking application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons and fonts
  cupertino_icons: ^1.0.6
google_fonts: ^6.1.0  # For the "Poppins" look in the design

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


assets:
  - assets/images/bus_bg.png
  - assets/logos/logo.png 
  

  # Example of adding a custom font if not using google_fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700